---
title: "Preparing Cluster Analysis"
author: "John Lim"
date: "2025-04-24"
format: pdf
---

The purpose of this file is to explore how different games on Steam can be grouped. What makes games alike/unalike?

```{r}
#| label: setup
#| include: false

knitr::opts_chunk$set(eval = FALSE, message = FALSE)

# improve digit and NA display 
options(scipen = 1, knitr.kable.NA = '')

# load packages
library(tidyverse)
library(readr)
library(purrr)
library(broom)
library(ggrepel)
library(GGally)
library(kableExtra)
```

```{r}
#| label: read-files

# read clean game data 
game_data <- readRDS("../data/processed/clean_games.rds")

```

```{r}
#| label: cluster-prep

# keep games that people have actually reviewed
# create game rating metric that describes how people think of games
# find net review rating, then divide by total reviews to get the ratio
# values range from -1 to 1, where -1 means all reviews were negative,
# 0 means there were an equal number of positive and negative reviews,
# and 1 means all reviews were positive
game_data2 <- game_data |>
  filter(positive != 0 | negative !=0) |>
  mutate(net_review_ratio = (positive - negative) / (positive + negative))

# get quantitative variables that I want to use for clustering
game_quant <- game_data2 |>
  select(required_age, price, dlc_count, metacritic_score,
         achievements, recommendations,
         median_playtime_forever, peak_ccu, net_review_ratio) |>
  drop_na()

# glimpse(game_quant)

# standardize variables for clustering
game_standardized <- game_quant |>
  mutate(across(everything(),
                ~ (.x - mean(.x)) / sd(.x),
                .names = "{.col}_z")) |>
  select(ends_with("_z"))

```

```{r}
#| label: elbow-plot

# set seed for reproducibility
set.seed(42069777)

# iterate through clustering algorithm for 10 different values of k
elbow_plot <- tibble(k = 1:10) |>
  mutate(
    kmeans_results = purrr::map(k, ~ kmeans(game_standardized, .x, nstart=25)),
    glanced = purrr::map(kmeans_results, glance)) |>
  unnest(cols = c(glanced))

# construct elbow plot
ggplot(elbow_plot, aes(x = k, y = tot.withinss)) +
  geom_point() + 
  geom_line() +
  scale_x_continuous(breaks = 1:10) +
  labs(x = "Number of clusters (k)", 
       y = "Total within-cluster sum of squares",
       title = "Elbow Plot for Standardized Variables")
# save image of elbow plot
ggsave("../images/elbow_plot.png")
```

```{r}
#| label: fit-cluster

# there appears to be a reasonable "elbow" bend at 5 clusters
# so, I will continue with 5

# for reproducibility
set.seed(42069777)

games_kmeans5 <- game_standardized |>
  kmeans(centers = 5, nstart = 25)

games_c5 <- augment(games_kmeans5, game_data2) |>
  rename(cluster_standardized = .cluster)

games_kmeans5$size
games_kmeans5$centers |>
  kable(booktabs = TRUE,
        col.names = c("Required Age", "Price", "DLC Count", "Metacritic Score", "Achievements", "Recommendations", "Median Playtime Forever", "Peak CCU", "Net Review Ratio"),
        caption = "Locations of Centroids based on Standardized Variables") |>
  kable_styling()

# look at these clusters, then give some specific examples
# include centroids on plots

# Cluster 1 appears to be: High metacritic_score, high price

# Cluster 2 appears to be: high age, higher prices, higher metacritic scores (not as high as c1), high recommendations

# Cluster 3 appears to be: low net review ratio

# Cluster 4 appears to be: very average, except for higher net review ratio z

# Cluster 5 appears to be: high dlc, high achievements, high playtime, high ccu

```

```{r}
#| label: scatterplot-matrix

# create scatterplot matrix of clusters
games_c5 |>
  select(required_age, price, dlc_count, metacritic_score,
         achievements, recommendations,
         median_playtime_forever, peak_ccu, net_review_ratio, 
         cluster_standardized) |>
ggpairs(aes(color = cluster_standardized),
        upper = list(continuous = "blank"), 
        progress = FALSE) +
  theme(text = element_text(size = 8))

ggplot(games_c5) +
  geom_point(aes(x=metacritic_score, y=price, color=cluster_standardized))

ggplot(games_c5) +
  geom_point(aes(x=required_age, y=recommendations, color=cluster_standardized))

ggplot(games_c5) +
  geom_point(aes(x=net_review_ratio, y=dlc_count, color=cluster_standardized))

ggplot(games_c5) +
  geom_point(aes(x=net_review_ratio, y=peak_ccu, color=cluster_standardized))

ggplot(games_c5) +
  geom_point(aes(x=achievements, y=median_playtime_forever, color=cluster_standardized))
```



```{r}
#| label: saving-data

# data used for cluster analysis
saveRDS(games_c5, file = "../data/processed/cluster_data.RDS")

```


