---
title: "Wrangling Steam Dataset"
subtitle: "From JSON to table"
author: "John Lim, Surya Rao, Tiffany Sun"
date: "2025-04-16"
format: pdf
---

The purpose of this file is to produce RDS files that wrangles data collected in the JSON file of the Steam games dataset. The CSV file incorrectly shifts columns, so we must start from the source. 

```{r}
#| label: setup
#| include: false

knitr::opts_chunk$set(eval = FALSE, message = FALSE)

# improve digit and NA display 
options(scipen = 1, knitr.kable.NA = '')

# load packages
library(tidyverse)
library(jsonlite)
library(readr)
library(purrr)
```

```{r}
#| label: read-files

# after reading csv, we can see at later observations, the data is shifted
# games_csv <- read_csv("../data/raw/games.csv")

# turn json data into dataframe
games_json <- read_json("../data/raw/games.json")
# flip the rows and columns since we want each observation as own row
games_transpose <- transpose(games_json)
# turn into data table with specific variables 
games_tibble <- games_transpose |>
  as_tibble()

```

```{r}
#| label: clean-table

# make a function that will clean up the string after condensing list
clean <- function(x) {
  x |> str_replace_all("list\\(","") |> 
    str_replace_all("\\)","") |> 
    str_replace_all('\\"',"")
}

# use dplyr 
games_clean <- games_tibble |>
  mutate(across(everything(),
                ~ .x |>
                  map(~ paste0(.x, collapse = ", ")) |>
                  clean()))

glimpse(games_clean)

# # use lapply
# games_tibble1 <- lapply(games_tibble, paste0)
# games_tibble2 <- lapply(games_tibble1, clean)
# games_tibble3 <- games_tibble2 |> as_tibble()
# 
# glimpse(games_tibble3)

data_games <- games_clean |>
  select(name, release_date, required_age, price, dlc_count,
         detailed_description, about_the_game, short_description,
         metacritic_score, achievements, recommendations,
         supported_langauges, full_audio_languages,
         developers, publishers, categories, genres,
         user_score, score_rank, positive, negative,
         average_playtime_forever, median_playtime_forever, peak_ccu, tags)

```

```{r}
#| label: saving-data

saveRDS(games_tibble, file = "../data/processed/clean_games.RDS")

```


